#!/bin/bash

#make -C $NEMU_HOME run ARGS="-b -l `dirname $1`/nemu-log.txt $1.bin -d tools/qemu-diff/build/qemu-so"
make -C $NEMU_HOME gdb ARGS="-b -l `dirname $1`/nemu-log.txt $1.bin -d tools/qemu-diff/build/qemu-so"
